### ISSUE TITLE
Assembled game doesn't load

### ISSUE THREAD

**Issue by r-moeritz** [tonysavon/Keystone-Kapers-C64#1]
Hi Tony.

thanks for porting this fun game, and especially for releasing the source code so the rest of us  can learn from you. Just one thing, after assembling the game with Kick Assembler v5.9 (`kickass game.asm`), the resulting PRG doesn't load properly in VICE (black screen). Am I missing an additional step?

Cheers,
Ralph

**Comment by tonysavon** [comment]
The prg goes past $c000, so you must either crunch it with exomizer before
you load it in vice, or you can run it straight away selecting somewhere in
vice the option "inject to memory".

**Comment by r-moeritz** [comment]
Ah, ok. Running `exomizer sfx sys game.prg -o keystone.prg` did the trick. Thanks!
